# Generated by Django 4.2.19 on 2025-02-10 00:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('domain', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='域名格式不正确', regex='^[a-zA-Z0-9][a-zA-Z0-9-_.]+[a-zA-Z0-9]$')], verbose_name='主域名')),
                ('path', models.CharField(max_length=255, verbose_name='网站目录')),
                ('server_type', models.CharField(choices=[('nginx', 'Nginx'), ('apache', 'Apache')], default='nginx', max_length=10, verbose_name='服务器类型')),
                ('php_version', models.CharField(choices=[('none', '不使用'), ('7.4', 'PHP 7.4'), ('8.0', 'PHP 8.0'), ('8.1', 'PHP 8.1'), ('8.2', 'PHP 8.2')], default='none', max_length=10, verbose_name='PHP版本')),
                ('status', models.BooleanField(default=False, verbose_name='运行状态')),
                ('ssl_enabled', models.BooleanField(default=False, verbose_name='SSL状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdditionalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='域名格式不正确', regex='^[a-zA-Z0-9][a-zA-Z0-9-_.]+[a-zA-Z0-9]$')], verbose_name='域名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_domains', to='websites.website', verbose_name='网站')),
            ],
            options={
                'verbose_name': '附加域名',
                'verbose_name_plural': '附加域名',
                'ordering': ['-created_at'],
            },
        ),
    ]
