# Generated by Django 4.2.19 on 2025-02-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_remove_website_path_alter_website_php_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='php_version',
            field=models.CharField(choices=[('none', '不使用'), ('8.1', 'PHP 8.1')], default='none', max_length=10, verbose_name='PHP版本'),
        ),
    ]
