# Generated by Django 4.2.19 on 2025-02-09 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0004_website_port_alter_website_php_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='网站路径'),
        ),
        migrations.AddField(
            model_name='website',
            name='user',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(max_length=100, unique=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='website',
            name='php_version',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PHP版本'),
        ),
        migrations.AlterField(
            model_name='website',
            name='port',
            field=models.IntegerField(default=80, verbose_name='端口'),
        ),
        migrations.AlterField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
