# Generated by Django 4.2.19 on 2025-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('cpu_percent', models.FloatField()),
                ('memory_percent', models.FloatField()),
                ('status', models.CharField(max_length=20)),
                ('created_time', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cpu_percent'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('auto_start', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('last_check', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu_usage', models.FloatField()),
                ('memory_total', models.BigIntegerField()),
                ('memory_used', models.BigIntegerField()),
                ('disk_total', models.BigIntegerField()),
                ('disk_used', models.BigIntegerField()),
                ('network_rx', models.BigIntegerField()),
                ('network_tx', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
