# Generated by Django 4.2.19 on 2025-02-09 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('category', models.CharField(choices=[('web', 'Web服务器'), ('database', '数据库'), ('cache', '缓存服务'), ('language', '编程语言'), ('tool', '管理工具')], max_length=20)),
                ('description', models.TextField()),
                ('os_version', models.CharField(choices=[('centos8', 'CentOS 8'), ('centos9', 'CentOS 9')], max_length=20)),
                ('install_script', models.TextField()),
                ('uninstall_script', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='app_icons/')),
                ('homepage', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version', 'os_version')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待安装'), ('installing', '安装中'), ('success', '安装成功'), ('failed', '安装失败')], default='pending', max_length=20)),
                ('install_path', models.CharField(blank=True, max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
