# Generated by Django 4.2.18 on 2025-01-26 12:15

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('command', models.TextField(verbose_name='执行命令')),
                ('interval', models.CharField(choices=[('minute', '每分钟'), ('hour', '每小时'), ('day', '每天'), ('week', '每周'), ('month', '每月'), ('custom', '自定义')], max_length=20, verbose_name='执行间隔')),
                ('cron_expression', models.CharField(blank=True, max_length=100, verbose_name='Cron表达式')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='上次执行')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='下次执行')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '计划任务',
                'verbose_name_plural': '计划任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据库名')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL')], default='mysql', max_length=20, verbose_name='数据库类型')),
                ('username', models.CharField(max_length=100, verbose_name='用户名')),
                ('password', models.CharField(max_length=100, verbose_name='密码')),
                ('charset', models.CharField(default='utf8mb4', max_length=20, verbose_name='字符集')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据库',
                'verbose_name_plural': '数据库',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('rule_type', models.CharField(choices=[('ip', 'IP封禁'), ('port', '端口限制'), ('url', 'URL拦截')], max_length=10, verbose_name='规则类型')),
                ('value', models.CharField(max_length=200, verbose_name='规则值')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '安全规则',
                'verbose_name_plural': '安全规则',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='网站名称')),
                ('domain', models.CharField(max_length=100, verbose_name='域名')),
                ('path', models.CharField(max_length=200, verbose_name='网站目录')),
                ('port', models.IntegerField(default=80, verbose_name='端口')),
                ('status', models.CharField(choices=[('running', '运行中'), ('stopped', '已停止')], default='stopped', max_length=20, verbose_name='状态')),
                ('server_type', models.CharField(default='nginx', max_length=20, verbose_name='服务器类型')),
                ('php_version', models.CharField(blank=True, max_length=20, null=True, verbose_name='PHP版本')),
                ('ssl_enabled', models.BooleanField(default=False, verbose_name='启用SSL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '网站',
                'verbose_name_plural': '网站',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('app_type', models.CharField(choices=[('env', '运行环境'), ('database', '数据库'), ('web', 'Web服务器'), ('tool', '管理工具')], max_length=20, verbose_name='应用类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('install_command', models.TextField(verbose_name='安装命令')),
                ('uninstall_command', models.TextField(verbose_name='卸载命令')),
                ('status', models.CharField(choices=[('not_installed', '未安装'), ('installing', '安装中'), ('installed', '已安装'), ('failed', '安装失败')], default='not_installed', max_length=20, verbose_name='状态')),
                ('install_time', models.DateTimeField(blank=True, null=True, verbose_name='安装时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认版本')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='appstore_icons/')),
                ('ubuntu_install_command', models.TextField(blank=True, verbose_name='Ubuntu安装命令')),
                ('centos_install_command', models.TextField(blank=True, verbose_name='CentOS安装命令')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用商店',
                'ordering': ['app_type', 'name', '-sort_order', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
