# Generated by Django 4.2.18 on 2025-01-26 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppStore',
        ),
    ]
