# Generated by Django 4.2.18 on 2025-01-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delete_appstore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='应用名称')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('app_type', models.CharField(choices=[('env', '运行环境'), ('database', '数据库'), ('web', 'Web服务器'), ('tool', '管理工具')], max_length=20, verbose_name='应用类型')),
                ('description', models.TextField(verbose_name='描述')),
                ('icon', models.CharField(default='bi-box', max_length=50, verbose_name='图标')),
                ('ubuntu_install_command', models.TextField(blank=True, verbose_name='Ubuntu安装命令')),
                ('centos_install_command', models.TextField(blank=True, verbose_name='CentOS安装命令')),
                ('uninstall_command', models.TextField(verbose_name='卸载命令')),
                ('status', models.CharField(choices=[('not_installed', '未安装'), ('installing', '安装中'), ('installed', '已安装'), ('failed', '安装失败')], default='not_installed', max_length=20, verbose_name='状态')),
                ('install_time', models.DateTimeField(blank=True, null=True, verbose_name='安装时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认版本')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用商店',
                'ordering': ['app_type', 'name', '-sort_order', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
