# Generated by Django 4.2.18 on 2025-01-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_appstore'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppStore',
        ),
    ]
