# Generated by Django 4.2.18 on 2025-01-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_appstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appstore',
            options={'ordering': ['app_type', 'name'], 'verbose_name': '应用', 'verbose_name_plural': '应用商店'},
        ),
        migrations.AlterUniqueTogether(
            name='appstore',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appstore',
            name='current_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='当前版本'),
        ),
        migrations.AddField(
            model_name='appstore',
            name='default_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='默认版本'),
        ),
        migrations.AddField(
            model_name='appstore',
            name='install_commands',
            field=models.JSONField(default=dict, verbose_name='安装命令'),
        ),
        migrations.AddField(
            model_name='appstore',
            name='versions',
            field=models.JSONField(default=list, verbose_name='可用版本'),
        ),
        migrations.RemoveField(
            model_name='appstore',
            name='centos_install_command',
        ),
        migrations.RemoveField(
            model_name='appstore',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='appstore',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='appstore',
            name='ubuntu_install_command',
        ),
        migrations.RemoveField(
            model_name='appstore',
            name='version',
        ),
    ]
